basePath: /api/v1/
definitions:
  model.Product:
    properties:
      amount:
        type: integer
      category:
        type: string
      description:
        type: string
      name:
        type: string
    type: object
  model.Result:
    properties:
      code:
        type: integer
      data:
        type: object
      error:
        example: false
        type: boolean
      message:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@version.one.com
    name: Version-One
  description: Starting Swagger docs
  license:
    name: BSD
    url: https://opensource.org/licenses/BSD-3-Clause
  termsOfService: https://version-one.com/terms/
  title: Fiber Test Rest API
  version: 0.1.0
paths:
  /product:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Result'
            - properties:
                data:
                  items:
                    allOf:
                    - $ref: '#/definitions/model.Product'
                    - properties:
                        id:
                          type: integer
                      type: object
                  type: array
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Result'
      security:
      - BasicAuth: []
      summary: Returns an array with all products on DB
    post:
      consumes:
      - application/json
      parameters:
      - description: Add product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/model.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/model.Result'
            - properties:
                data:
                  items:
                    allOf:
                    - $ref: '#/definitions/model.Product'
                    - properties:
                        id:
                          type: integer
                      type: object
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Result'
      security:
      - BasicAuth: []
      summary: Creates a new product in DB
  /product/{id}:
    delete:
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Result'
      security:
      - BasicAuth: []
      summary: Deletes a product from DB
    get:
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Result'
            - properties:
                data:
                  items:
                    allOf:
                    - $ref: '#/definitions/model.Product'
                    - properties:
                        id:
                          type: integer
                      type: object
                  type: array
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Result'
      security:
      - BasicAuth: []
      summary: Returns a single product from DB
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
